receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  azuremonitor:
    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
